name: smart-check-sizing
version: '2.0.0'
base: core22
summary: Preventive maintenance
description: The application enables graphical visualization of motor performance analysis and sizing, serving the purposes of visual comprehension, trend identification, and anomaly detection.
  source code https://github.com/Felix-73/NewCTRLX-SDK-APP-SmartCheckSizing
      
confinement: strict
grade: stable

architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  flask-server: 
    command: bin/runserver.wrapper
    environment:
      PYTHONPATH: $SNAP/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages
      BOSCH_API_URL: "https://localhost"
      BOSCH_API_USERNAME: "boschrexroth"
      BOSCH_API_PASSWORD: "boschrexroth"
    plugs:
      - network-control
      - network-observe
      - network
      - network-bind
      - home
      - removable-media
    daemon: simple

parts:
  flask:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    build-packages:
      - python3-dev
    python-packages: 
      - flask
      - requests
      - werkzeug
      - flask-sqlalchemy
      - flask-socketio
    source: .

  python-code: 
    source: ./Flask/
    plugin: dump
    organize:
      '*': bin/Flask/
    prime:
      - bin/Flask/static/**
      - bin/Flask/templates/**
      - bin/Flask/app.py
      - bin/Flask/api/**

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/

  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}